version: "3"
services:
  client:
    image: adityagowda2000/client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
    depends_on:
      - server
  server:
    image: adityagowda2000/server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes: -logs:/usr/src/app/logs

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mern-app

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - logs:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - mern-app

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - Elasticsearch
    networks:
      - mern-app

volumes: logs:{}

networks:
  mern-app:
    driver: bridge
